### ISSUE TITLE
icon for more tools

### ISSUE THREAD

**Issue by michael-collins** [LRNWebComponents/lrnsys-layout#1]
Let's use the vertical or horizontal "more" icon from material.

https://material.io/icons/#ic_more_horiz

https://material.io/icons/#ic_more_vert

**Comment by btopro** [comment]
this would be a bandaid on a bandaid so not interested. the example "more tools" in this demo is an example of a layout flyout and nothing more. ... wouldn't make anymore sense then currently having a giant catch all menu of "MORE TOOLS" which is an eye sore but fortunately only visible to like 5 people at the moment. We need to do an inventory of our "menus" and "settings" for better overall admin UX, though this should happen in the main https://github.com/elmsln/elmsln repo and not here as this is just a collection of navigational design patterns for developing interfaces not THE interface.
